#!/bin/bash

# Change default timezone to MSK

echo '#cloud-config' > /etc/cloud/cloud.cfg.d/50_timezone.cfg
echo 'timezone: Europe/Moscow'  >> /etc/cloud/cloud.cfg.d/50_timezone.cfg

# Change default password

#echo '#cloud-config' > /etc/cloud/cloud.cfg.d/50_change_default_pass.cfg
#echo 'password: centos' >> /etc/cloud/cloud.cfg.d/50_change_default_pass.cfg

# Change default user password expiry information

#echo '#cloud-config' > /etc/cloud/cloud.cfg.d/50_chage_password.cfg
#echo 'runcmd:' >> /etc/cloud/cloud.cfg.d/50_chage_password.cfg
#echo '- chage -d 0 centos' >> /etc/cloud/cloud.cfg.d/50_chage_password.cfg
